function New-InspectorRecommendationReference {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)][string]$ReferenceId,
        [Parameter(Mandatory)][string]$StableId,
        [Parameter(Mandatory)][string]$Title,
        [Parameter(Mandatory)]
        [ValidateSet('MicrosoftLearn','MicrosoftGraph','MicrosoftZeroTrust','NIST','CIS')]
        [string]$SourceType,
        [Parameter(Mandatory)][string]$Url,
        [string[]]$AppliesTo = @(),
        [Parameter(Mandatory)][string]$Summary,
        [string[]]$Tags = @()
    )

    [PSCustomObject][ordered]@{
        ReferenceId = $ReferenceId
        StableId    = $StableId
        Title       = $Title
        SourceType  = $SourceType
        Url         = $Url
        AppliesTo   = @($AppliesTo)
        Summary     = $Summary
        Tags        = @($Tags)
    }
}

function Get-InspectorRecommendationReferenceCatalog {
    [CmdletBinding()]
    param ()

    @(
        New-InspectorRecommendationReference 'MS-APP-SECURITY-BEST-PRACTICES' 'MS-ENTRA-001' 'Security best practices for application properties in Microsoft Entra ID' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity-platform/security-best-practices-for-app-registration' @('ApplicationOwnership','CredentialHygiene','ApplicationGovernance','ServicePrincipalGovernance') 'Microsoft guidance for securing application registrations, reviewing ownership, and managing application credentials.' @('application','owner','credential')
        New-InspectorRecommendationReference 'MS-APP-LEAST-PRIVILEGE' 'MS-ENTRA-002' 'Increase application security with the principle of least privilege' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity-platform/secure-least-privileged-access' @('HighImpactPermissions','ApplicationPermissions','DelegatedPermissions','ConsentGovernance','LeastPrivilege') 'Microsoft guidance for reducing app attack surface by granting only the permissions required.' @('least privilege','permissions','consent')
        New-InspectorRecommendationReference 'MS-GRAPH-PERMISSIONS-REFERENCE' 'MS-GRAPH-001' 'Microsoft Graph permissions reference' 'MicrosoftGraph' 'https://learn.microsoft.com/en-us/graph/permissions-reference' @('HighImpactPermissions','ApplicationPermissions','DelegatedPermissions','PermissionMetadata') 'Authoritative Microsoft Graph permission reference used to validate permission meaning and impact.' @('graph','permissions','reference')
        New-InspectorRecommendationReference 'MS-GRAPH-PERMISSION-BEST-PRACTICES' 'MS-GRAPH-002' 'Best practices for using Microsoft Graph permissions' 'MicrosoftGraph' 'https://learn.microsoft.com/en-us/graph/best-practices-graph-permission' @('HighImpactPermissions','ApplicationPermissions','LeastPrivilege') 'Microsoft guidance for requesting the fewest and least-privileged Microsoft Graph permissions required.' @('graph','least privilege','permissions')
        New-InspectorRecommendationReference 'MS-GRAPH-BEST-PRACTICES' 'MS-GRAPH-003' 'Best practices for working with Microsoft Graph' 'MicrosoftGraph' 'https://learn.microsoft.com/en-us/graph/best-practices-concept' @('GraphCollection','LeastPrivilege','Paging','Throttling','SelectOptimization','RuntimeTelemetry') 'Microsoft Graph guidance for least privilege, paging, throttling, $select usage, and reliable API behavior.' @('graph','paging','throttling')
        New-InspectorRecommendationReference 'MS-GRAPH-THROTTLING' 'MS-GRAPH-004' 'Microsoft Graph throttling guidance' 'MicrosoftGraph' 'https://learn.microsoft.com/en-us/graph/throttling' @('GraphCollection','RuntimeTelemetry','RetryHandling','Throttling') 'Microsoft Graph guidance for handling 429 throttling responses and Retry-After behavior.' @('graph','throttling','retry')
        New-InspectorRecommendationReference 'MS-PERMISSIONS-CONSENT-OVERVIEW' 'MS-ENTRA-003' 'Overview of permissions and consent in the Microsoft identity platform' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity-platform/permissions-consent-overview' @('ConsentGovernance','DelegatedPermissions','ApplicationPermissions','AdminConsent') 'Microsoft overview of delegated permissions, application permissions, and consent behavior.' @('consent','delegated','application permissions')
        New-InspectorRecommendationReference 'MS-USER-ADMIN-CONSENT' 'MS-ENTRA-004' 'Overview of user and admin consent' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/user-admin-consent-overview' @('ConsentGovernance','TenantWideConsent','AdminConsent','DelegatedPermissions') 'Microsoft guidance explaining user consent, admin consent, and the sensitivity of organization-wide admin consent.' @('admin consent','tenant-wide consent')
        New-InspectorRecommendationReference 'MS-MANAGE-APP-PERMISSIONS' 'MS-ENTRA-005' 'Review permissions granted to enterprise applications' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/manage-application-permissions' @('ConsentGovernance','ApplicationPermissions','DelegatedPermissions','EnterpriseApplications') 'Microsoft guidance for reviewing permissions granted to enterprise applications.' @('enterprise applications','permissions')
        New-InspectorRecommendationReference 'MS-GRANT-TENANT-WIDE-CONSENT' 'MS-ENTRA-006' 'Grant tenant-wide admin consent to an application' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-admin-consent' @('TenantWideConsent','AdminConsent','ConsentGovernance') 'Microsoft documentation for tenant-wide admin consent behavior and administrative considerations.' @('tenant-wide consent','admin consent')
        New-InspectorRecommendationReference 'MS-GOVERN-SERVICE-ACCOUNTS' 'MS-ENTRA-007' 'Governing Microsoft Entra service accounts' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/architecture/govern-service-accounts' @('ServicePrincipalGovernance','WorkloadIdentity','Ownership','LeastPrivilege','Lifecycle') 'Microsoft guidance for governing service accounts, including service principals and managed identities.' @('service principal','service account','governance')
        New-InspectorRecommendationReference 'MS-APP-SERVICE-PRINCIPAL-CONCEPTS' 'MS-ENTRA-008' 'Applications and service principals in Microsoft Entra ID' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity-platform/app-objects-and-service-principals' @('ApplicationGovernance','ServicePrincipalGovernance','ObjectModel') 'Microsoft conceptual documentation explaining application objects and service principals.' @('application','service principal')
        New-InspectorRecommendationReference 'MS-APP-CREDENTIALS' 'MS-ENTRA-009' 'Add and manage app credentials in Microsoft Entra ID' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity-platform/how-to-add-credentials' @('CredentialHygiene','ExpiredCredentials','ExpiringCredentials','Certificates','ClientSecrets') 'Microsoft documentation for client secrets, certificate credentials, and federated identity credentials.' @('credentials','secrets','certificates')
        New-InspectorRecommendationReference 'MS-RECOMMEND-EXPIRING-APP-CREDENTIALS' 'MS-ENTRA-010' 'Microsoft Entra recommendation: Renew expiring application credentials' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/monitoring-health/recommendation-renew-expiring-application-credential' @('CredentialHygiene','ExpiringCredentials','ApplicationGovernance') 'Microsoft Entra recommendation for renewing application credentials before expiration.' @('expiring credentials')
        New-InspectorRecommendationReference 'MS-RECOMMEND-REMOVE-UNUSED-CREDENTIALS' 'MS-ENTRA-011' 'Microsoft Entra recommendation: Remove unused credentials from applications' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/monitoring-health/recommendation-remove-unused-credential-from-apps' @('CredentialHygiene','UnusedCredentials','ApplicationGovernance') 'Microsoft Entra recommendation for removing unused credentials from applications.' @('unused credentials')
        New-InspectorRecommendationReference 'MS-RECOMMEND-REMOVE-UNUSED-APPS' 'MS-ENTRA-012' 'Microsoft Entra recommendation: Remove unused applications' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/monitoring-health/recommendation-remove-unused-apps' @('ApplicationGovernance','UnusedApplications','Lifecycle') 'Microsoft Entra recommendation for reviewing and removing unused applications.' @('unused applications')
        New-InspectorRecommendationReference 'MS-ENTRA-RBAC-BEST-PRACTICES' 'MS-ENTRA-013' 'Best practices for Microsoft Entra roles' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/best-practices' @('DirectoryRoles','PrivilegedAccess','LeastPrivilege','RoleAssignments','AccessReviews') 'Microsoft guidance for least privilege, privileged role assignments, and Microsoft Entra role governance.' @('roles','rbac','privileged access')
        New-InspectorRecommendationReference 'MS-PRIVILEGED-ROLES-PERMISSIONS' 'MS-ENTRA-014' 'Privileged roles and permissions in Microsoft Entra ID' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/privileged-roles-permissions' @('DirectoryRoles','PrivilegedAccess','PrivilegedPermissions','RoleAssignments') 'Microsoft documentation for identifying privileged roles, privileged permissions, and privileged role assignments.' @('privileged roles','permissions')
        New-InspectorRecommendationReference 'MS-ROLE-ASSIGNABLE-GROUPS' 'MS-ENTRA-015' 'Use Microsoft Entra groups to manage role assignments' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/groups-concept' @('RoleAssignableGroups','PrivilegedGroups','DirectoryRoles','GroupGovernance') 'Microsoft guidance for using role-assignable groups to manage Microsoft Entra role assignments.' @('role-assignable groups')
        New-InspectorRecommendationReference 'MS-PIM-FOR-GROUPS' 'MS-ENTRA-016' 'Privileged Identity Management for Groups' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/concept-pim-for-groups' @('RoleAssignableGroups','PrivilegedGroups','PrivilegedAccess','JustInTimeAccess') 'Microsoft guidance for using PIM for Groups to manage privileged group membership and ownership.' @('pim','groups','privileged access')
        New-InspectorRecommendationReference 'MS-ACCESS-REVIEWS-DEPLOYMENT' 'MS-ENTRA-017' 'Plan a Microsoft Entra access reviews deployment' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/id-governance/deploy-access-reviews' @('AccessReviews','GroupGovernance','ApplicationAccess','EntitlementReview','IdentityGovernance') 'Microsoft guidance for planning access reviews for users, groups, and application access.' @('access reviews')
        New-InspectorRecommendationReference 'MS-ACCESS-REVIEWS-APP-PREPARATION' 'MS-ENTRA-018' "Preparing for an access review of users' access to an application" 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/id-governance/access-reviews-application-preparation' @('ApplicationAccess','AccessReviews','AssignmentRequired','AppRoleAssignments') 'Microsoft guidance for preparing application access for review through Microsoft Entra access reviews.' @('application access','access reviews')
        New-InspectorRecommendationReference 'MS-SECURE-GROUP-ACCESS-CONTROL' 'MS-ENTRA-019' 'Secure access control using groups in Microsoft Entra ID' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/identity-platform/secure-group-access-control' @('GroupGovernance','GroupOwnership','ApplicationAccess','AccessControl') 'Microsoft guidance for using groups securely for access control and avoiding mismatched resource/group ownership risks.' @('groups','access control')
        New-InspectorRecommendationReference 'MS-ENTRA-AUTH-OPS-GUIDE' 'MS-ENTRA-020' 'Microsoft Entra authentication management operations reference guide' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/architecture/ops-guide-auth' @('ApplicationAccess','AssignmentRequired','AccessReviews','GroupBasedAccess') 'Microsoft operations guidance noting that assigning users to applications is best mapped using groups and can be governed with access reviews.' @('operations','application access')
        New-InspectorRecommendationReference 'MS-ENTRA-SECURE-BEST-PRACTICES' 'MS-ENTRA-021' 'Best practices to secure with Microsoft Entra ID' 'MicrosoftLearn' 'https://learn.microsoft.com/en-us/entra/architecture/secure-best-practices' @('LeastPrivilege','PrivilegedAccess','ServicePrincipalGovernance','WorkloadIdentity','ConditionalAccess') 'Microsoft broad security guidance for Microsoft Entra, least privilege, privileged access, and service principal protection.' @('secure best practices')
        New-InspectorRecommendationReference 'MS-ZERO-TRUST-OVERVIEW' 'MS-ZT-001' 'Zero Trust as a security foundation' 'MicrosoftZeroTrust' 'https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview' @('ZeroTrust','LeastPrivilege','ContinuousVerification','Governance') 'Microsoft Zero Trust guidance emphasizing verify explicitly, use least privilege, and assume breach.' @('zero trust','least privilege')
        New-InspectorRecommendationReference 'MS-ZERO-TRUST-APP-LEAST-PRIVILEGE' 'MS-ZT-002' 'Increase application security using Zero Trust principles' 'MicrosoftZeroTrust' 'https://learn.microsoft.com/en-us/entra/identity-platform/zero-trust-for-developers' @('ZeroTrust','LeastPrivilege','ApplicationPermissions','ApplicationGovernance') 'Microsoft guidance for building Zero Trust-ready applications and enforcing least-privileged access.' @('zero trust','applications')
        New-InspectorRecommendationReference 'MS-ZERO-TRUST-OVERPRIVILEGED-PERMISSIONS' 'MS-ZT-003' 'Reduce overprivileged permissions and apps' 'MicrosoftZeroTrust' 'https://learn.microsoft.com/en-us/security/zero-trust/develop/overprivileged-permissions' @('OverprivilegedApplications','HighImpactPermissions','LeastPrivilege','ConsentGovernance') 'Microsoft guidance for reducing overprivileged permissions and improving application Zero Trust readiness.' @('overprivileged','permissions')
        New-InspectorRecommendationReference 'NIST-CSF-2-PR-AA' 'NIST-CSF-001' 'NIST Cybersecurity Framework 2.0 - Identity Management, Authentication, and Access Control' 'NIST' 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' @('IdentityGovernance','AccessControl','LeastPrivilege','AccessReviews','CredentialManagement') 'NIST CSF 2.0 governance context for managing identities, credentials, permissions, entitlements, authorizations, least privilege, and separation of duties.' @('nist','identity','access control')
        New-InspectorRecommendationReference 'CIS-CONTROL-5-ACCOUNT-MANAGEMENT' 'CIS-CTRL-005' 'CIS Critical Security Control 5: Account Management' 'CIS' 'https://www.cisecurity.org/controls/account-management' @('AccountManagement','ServiceAccounts','PrivilegedAccounts','CredentialManagement') 'CIS guidance for assigning and managing authorization to credentials for user, administrator, and service accounts.' @('cis','account management')
        New-InspectorRecommendationReference 'CIS-CONTROL-6-ACCESS-CONTROL-MANAGEMENT' 'CIS-CTRL-006' 'CIS Critical Security Control 6: Access Control Management' 'CIS' 'https://www.cisecurity.org/controls/access-control-management' @('AccessControl','LeastPrivilege','PrivilegedAccess','AuthorizationManagement') 'CIS guidance for creating, assigning, managing, and revoking access credentials and privileges.' @('cis','access control')
        New-InspectorRecommendationReference 'CIS-M365-FOUNDATIONS-BENCHMARK' 'CIS-M365-001' 'CIS Microsoft 365 Foundations Benchmark' 'CIS' 'https://www.cisecurity.org/benchmark/microsoft_365' @('Microsoft365Security','TenantConfiguration','IdentityGovernance','AccessControl') 'CIS benchmark landing page for Microsoft 365 secure configuration guidance. Do not cite specific benchmark controls unless the benchmark content is available in the repository or provided by the user.' @('cis','microsoft 365','benchmark')
    )
}
